/**
 * Extended list of cryptocurrency trading pairs for analysis
 * 300+ popular and liquid trading pairs from Binance and MEXC
 * Based on top trading pairs by volume and market cap
 */
export const POPULAR_SYMBOLS = [
  // Major cryptocurrencies (Top 10)
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'ADAUSDT', 'DOGEUSDT', 'DOTUSDT', 'AVAXUSDT', 'SHIBUSDT',
  
  // Large cap altcoins (Top 50)
  'MATICUSDT', 'LINKUSDT', 'UNIUSDT', 'ATOMUSDT', 'ETCUSDT', 'LTCUSDT', 'XLMUSDT', 'ALGOUSDT', 'VETUSDT', 'ICPUSDT',
  'FILUSDT', 'TRXUSDT', 'EOSUSDT', 'AAVEUSDT', 'MKRUSDT', 'SNXUSDT', 'COMPUSDT', 'YFIUSDT', 'SUSHIUSDT', 'CRVUSDT',
  '1INCHUSDT', 'DYDXUSDT', 'ARBUSDT', 'OPUSDT', 'APTUSDT', 'SUIUSDT', 'SEIUSDT', 'TIAUSDT', 'INJUSDT', 'NEARUSDT',
  'FTMUSDT', 'AXSUSDT', 'SANDUSDT', 'MANAUSDT', 'GALAUSDT', 'IMXUSDT', 'PIXELUSDT', 'PEPEUSDT', 'FLOKIUSDT', 'BONKUSDT',
  'FETUSDT', 'AGIXUSDT', 'OCEANUSDT', 'RNDRUSDT', 'AIUSDT', 'XAIUSDT', 'ORDIUSDT', '1000SATSUSDT', 'WLDUSDT', 'JTOUSDT',
  
  // Mid cap altcoins (51-100)
  'PYTHUSDT', 'BLURUSDT', 'ACEUSDT', 'NFPUSDT', 'MANTAUSDT', 'ALTUSDT', 'PORTALUSDT', 'PUNDIXUSDT', 'METISUSDT', 'AEVOUSDT',
  'BOMEUSDT', 'ENAUSDT', 'WUSDT', 'TNSRUSDT', 'SAGAUSDT', 'REZUSDT', 'BBUSDT', 'NOTUSDT', 'IOUSDT', 'ZROUSDT',
  'LISTAUSDT', 'TAOUSDT', 'OMNIUSDT', 'ZKUSDT', 'BCHUSDT', 'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'WAVESUSDT', 'ZILUSDT',
  'BATUSDT', 'ENJUSDT', 'CHZUSDT', 'HBARUSDT', 'EGLDUSDT', 'THETAUSDT', 'GRTUSDT', 'RENUSDT', 'KSMUSDT', 'DOTUSDT',
  'LUNAUSDT', 'USTCUSDT', 'LUNCUSDT', 'USTUSDT', 'USTCUSDT', 'LDOUSDT', 'ARBUSDT', 'OPUSDT', 'APTUSDT', 'SUIUSDT',
  
  // DeFi tokens (101-150)
  'CAKEUSDT', 'BAKEUSDT', 'ALPACAUSDT', 'ALPHAUSDT', 'BELUSDT', 'BETAUSDT', 'BIFIUSDT', 'BURGERUSDT', 'BUNNYUSDT', 'CAKEUSDT',
  'DODOUSDT', 'EGGUSDT', 'FORUSDT', 'FRONTUSDT', 'FUNUSDT', 'GALAUSDT', 'GFTUSDT', 'GMTUSDT', 'GTOUSDT', 'HARDUSDT',
  'HOTUSDT', 'IDUSDT', 'ILVUSDT', 'JASMYUSDT', 'KLAYUSDT', 'KMDUSDT', 'KNCUSDT', 'LINAUSDT', 'LITUSDT', 'LRCUSDT',
  'LUNRUSDT', 'MAGICUSDT', 'MANAUSDT', 'MASKUSDT', 'MATICUSDT', 'MDTUSDT', 'MINAUSDT', 'MKRUSDT', 'MTLUSDT', 'NEARUSDT',
  'NEOUSDT', 'NKNUSDT', 'OCEANUSDT', 'OGNUSDT', 'OMGUSDT', 'ONTUSDT', 'OPUSDT', 'ORNUSDT', 'OXTUSDT', 'PENDLEUSDT',
  
  // Gaming & NFT (151-200)
  'PEPEUSDT', 'PERPUSDT', 'PHBUSDT', 'POLYXUSDT', 'PONDUSDT', 'POWRUSDT', 'PROMUSDT', 'QNTUSDT', 'QTUMUSDT', 'RADUSDT',
  'RAREUSDT', 'REEFUSDT', 'RENUSDT', 'REQUSDT', 'RIFUSDT', 'RLCUSDT', 'ROSEUSDT', 'RSRUSDT', 'RUNEUSDT', 'RVNUSDT',
  'SANDUSDT', 'SFPUSDT', 'SKLUSDT', 'SLPUSDT', 'SNTUSDT', 'SNXUSDT', 'SOLUSDT', 'SPELLUSDT', 'SRMUSDT', 'STGUSDT',
  'STMXUSDT', 'STORJUSDT', 'STPTUSDT', 'STRAXUSDT', 'STXUSDT', 'SUIUSDT', 'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXPUSDT',
  'SYNUSDT', 'TUSDT', 'TCTUSDT', 'TFUELUSDT', 'THETAUSDT', 'TIAUSDT', 'TLMUSDT', 'TNSRUSDT', 'TOMOUSDT', 'TRUUSDT',
  
  // Layer 1 & Layer 2 (201-250)
  'TRXUSDT', 'TWTUSDT', 'UFTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT', 'VETUSDT', 'VTHOUSDT', 'WAVESUSDT', 'WAXPUSDT',
  'WLDUSDT', 'WINUSDT', 'WOOUSDT', 'XECUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'XVGUSDT',
  'XVSUSDT', 'YFIUSDT', 'YFIIUSDT', 'ZECUSDT', 'ZENUSDT', 'ZILUSDT', 'ZRXUSDT', '1INCHUSDT', '1000PEPEUSDT', '1000SHIBUSDT',
  '1000SATSUSDT', '1000FLOKIUSDT', '1000LUNCUSDT', '1000XECUSDT', 'AAVEUSDT', 'ACEUSDT', 'ACHUSDT', 'ACMUSDT', 'ADAUSDT', 'ADXUSDT',
  'AEVOUSDT', 'AGIXUSDT', 'AGLDUSDT', 'AIUSDT', 'AKROUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ALPACAUSDT', 'ALPHAUSDT', 'ALTUSDT',
  
  // Meme & AI coins (251-300)
  'AMBUSDT', 'ANKRUSDT', 'ANTUSDT', 'APEUSDT', 'API3USDT', 'APTUSDT', 'ARBUSDT', 'ARKMUSDT', 'ARPAUSDT', 'ARUSDT',
  'ATAUSDT', 'ATOMUSDT', 'AUCTIONUSDT', 'AUDIOUSDT', 'AVAXUSDT', 'AXSUSDT', 'BADGERUSDT', 'BAKEUSDT', 'BALUSDT', 'BANDUSDT',
  'BATUSDT', 'BCHUSDT', 'BELUSDT', 'BICOUSDT', 'BIFIUSDT', 'BLURUSDT', 'BLZUSDT', 'BNBUSDT', 'BNXUSDT', 'BOMEUSDT',
  'BONKUSDT', 'BORAUSDT', 'BRCUSDT', 'BSVUSDT', 'BTCUSDT', 'BTTCUSDT', 'BURGERUSDT', 'C98USDT', 'CAKEUSDT', 'CELOUSDT',
  'CELRUSDT', 'CFXUSDT', 'CHRUSDT', 'CHZUSDT', 'CKBUSDT', 'COMBOUSDT', 'COMPUSDT', 'COTIUSDT', 'CRVUSDT', 'CTKUSDT',
  
  // Additional popular pairs (301-350+)
  'CTSIUSDT', 'CTXCUSDT', 'CVCUSDT', 'CVXUSDT', 'CYBERUSDT', 'DAIUSDT', 'DARUSDT', 'DASHUSDT', 'DATAUSDT', 'DCRUSDT',
  'DEGOUSDT', 'DENTUSDT', 'DEXEUSDT', 'DFUSDT', 'DGBUSDT', 'DIAUSDT', 'DOCKUSDT', 'DODOUSDT', 'DOGEUSDT', 'DOTUSDT',
  'DUSKUSDT', 'DYDXUSDT', 'EDUUSDT', 'EGLDUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'ETHWUSDT', 'FARMUSDT', 'FDUSDUSDT',
  'FETUSDT', 'FIDAUSDT', 'FILUSDT', 'FIOUSDT', 'FISUSDT', 'FLMUSDT', 'FLOKIUSDT', 'FLOWUSDT', 'FLUXUSDT', 'FORTHUSDT',
  'FRONTUSDT', 'FTMUSDT', 'FTTUSDT', 'FUNUSDT', 'FXSUSDT', 'GALAUSDT', 'GALUSDT', 'GASUSDT', 'GFTUSDT', 'GHSTUSDT',
  'GLMUSDT', 'GMTUSDT', 'GMXUSDT', 'GNOUSDT', 'GNSUSDT', 'GQUSDT', 'GRTUSDT', 'GSTUSDT', 'GTCUSDT', 'GTOUSDT',
  'HARDUSDT', 'HBARUSDT', 'HFTUSDT', 'HIFIUSDT', 'HIGHUSDT', 'HNTUSDT', 'HOOKUSDT', 'HOTUSDT', 'ICPUSDT', 'ICXUSDT',
  'IDEXUSDT', 'IDUSDT', 'ILVUSDT', 'IMXUSDT', 'INJUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IQUSDT', 'IRISUSDT',
  'JASMYUSDT', 'JOEUSDT', 'JSTUSDT', 'JTOUSDT', 'JUPUSDT', 'KAVAUSDT', 'KDAUSDT', 'KEYUSDT', 'KLAYUSDT', 'KMDUSDT',
  'KNCUSDT', 'KP3RUSDT', 'KSMUSDT', 'LAZIOUSDT', 'LDOUSDT', 'LEVERUSDT', 'LINAUSDT', 'LINKUSDT', 'LITUSDT', 'LISTAUSDT',
  'LITUSDT', 'LOOMUSDT', 'LPTUSDT', 'LRCUSDT', 'LSKUSDT', 'LTCUSDT', 'LUNAUSDT', 'LUNCUSDT', 'MAGICUSDT', 'MANAUSDT',
  'MANTAUSDT', 'MASKUSDT', 'MATICUSDT', 'MAVUSDT', 'MBLUSDT', 'MDTUSDT', 'MEMEUSDT', 'METISUSDT', 'MINAUSDT', 'MKRUSDT',
  'MLNUSDT', 'MOVRUSDT', 'MTLUSDT', 'MULTIUSDT', 'NEARUSDT', 'NEOUSDT', 'NFPUSDT', 'NKNUSDT', 'NOTUSDT', 'NTRNUSDT',
  'OCEANUSDT', 'OGNUSDT', 'OMGUSDT', 'OMNIUSDT', 'ONEUSDT', 'ONTUSDT', 'OPUSDT', 'ORDIUSDT', 'ORNUSDT', 'OXTUSDT',
  'PENDLEUSDT', 'PEOPLEUSDT', 'PEPEUSDT', 'PERPUSDT', 'PHBUSDT', 'PIXELUSDT', 'PLAUSDT', 'PNTUSDT', 'POLYXUSDT', 'PONDUSDT',
  'PORTALUSDT', 'POWRUSDT', 'PROMUSDT', 'PUNDIXUSDT', 'PYTHUSDT', 'QNTUSDT', 'QTUMUSDT', 'RADUSDT', 'RAREUSDT', 'RATSUSDT',
  'RDNTUSDT', 'REEFUSDT', 'REIUSDT', 'RENUSDT', 'REQUSDT', 'REZUSDT', 'RIFUSDT', 'RLCUSDT', 'RNDRUSDT', 'ROSEUSDT',
  'RPLUSDT', 'RSRUSDT', 'RUNEUSDT', 'RVNUSDT', 'SAGAUSDT', 'SANDUSDT', 'SANTOSUSDT', 'SEIUSDT', 'SFPUSDT', 'SHIBUSDT',
  'SKLUSDT', 'SLPUSDT', 'SNTUSDT', 'SNXUSDT', 'SOLUSDT', 'SPELLUSDT', 'SSVUSDT', 'STEEMUSDT', 'STGUSDT', 'STMXUSDT',
  'STORJUSDT', 'STPTUSDT', 'STRKUSDT', 'STXUSDT', 'SUIUSDT', 'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXPUSDT', 'SYNUSDT',
  'TUSDT', 'TCTUSDT', 'TFUELUSDT', 'THETAUSDT', 'TIAUSDT', 'TLMUSDT', 'TNSRUSDT', 'TOMOUSDT', 'TRBUSDT', 'TRUUSDT',
  'TRXUSDT', 'TWTUSDT', 'UFTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT', 'VANRYUSDT', 'VETUSDT', 'VICUSDT', 'VIDTUSDT',
  'VTHOUSDT', 'WAVESUSDT', 'WAXPUSDT', 'WLDUSDT', 'WINUSDT', 'WOOUSDT', 'XAIUSDT', 'XECUSDT', 'XEMUSDT', 'XLMUSDT',
  'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'XVGUSDT', 'XVSUSDT', 'YFIUSDT', 'YFIIUSDT', 'ZECUSDT', 'ZENUSDT', 'ZILUSDT',
  'ZKUSDT', 'ZROUSDT', 'ZRXUSDT',
];

// Remove duplicates and sort
export const UNIQUE_POPULAR_SYMBOLS = Array.from(new Set(POPULAR_SYMBOLS)).sort();

// Split symbols between exchanges (Binance and MEXC)
// Binance gets first half, MEXC gets second half
export const BINANCE_SYMBOLS = UNIQUE_POPULAR_SYMBOLS.slice(0, Math.ceil(UNIQUE_POPULAR_SYMBOLS.length / 2));
export const MEXC_SYMBOLS = UNIQUE_POPULAR_SYMBOLS.slice(Math.ceil(UNIQUE_POPULAR_SYMBOLS.length / 2));
